### PR TITLE
News page 10.0

### PR DESCRIPTION
**Pull request by ivy-lli**
- Update home mountain picture
- Update primeflex to version 2
- Update news detail design a bit

### CODE REVIEW

**Comment by alexsuter** [comment]
good for me. I thought we decided to keep the ivy-leaf for the product itself, not?

we may should link to balsis release page?

@andreasbalsiger and @ivy-bb should have a look at it!

**Comment by alexsuter** [comment]
sorry, I overhear the ivy-leaf discussion this morning.

**Comment by ivy-lli** [comment]
> sorry, I overhear the ivy-leaf discussion this morning.

Wasn't a discussion, I've only said it. I know, we wanted the ivy-leaf in the product, but honestly I don't like it if the portal has the "new" logo as favicon, and we still use the old one... I think its much simpler to use the same logo everywhere.

**Comment by ivy-lli** [comment]
> > > sorry, I overhear the ivy-leaf discussion this morning.
> > 
> > 
> > Wasn't a discussion, I've only said it. I know, we wanted the ivy-leaf in the product, but honestly I don't like it if the portal has the "new" logo as favicon, and we still use the old one... I think its much simpler to use the same logo everywhere.
> 
> portal should also use the ivy-leaf

Please discuss this with @andreasbalsiger. I can easily revert all PR's

**Comment by alexsuter** [comment]
> > > > sorry, I overhear the ivy-leaf discussion this morning.
> > > 
> > > 
> > > Wasn't a discussion, I've only said it. I know, we wanted the ivy-leaf in the product, but honestly I don't like it if the portal has the "new" logo as favicon, and we still use the old one... I think its much simpler to use the same logo everywhere.
> > 
> > 
> > portal should also use the ivy-leaf
> 
> Please discuss this with @andreasbalsiger. I can easily revert all PR's

CC: @andreasbalsiger @ivy-bb 

This is just my opinion. The product should stay with the ivy leaf and also the portal, because the portal is representing the product. We are currently removing 25 years of history and forcing the "A" of Axon Ivy, beside that we are not anymore an Axon Company?! We are still named Axon but how long?!

I just want to outline my very own opinion. Such a big "image" change in the heart of ivy should be discussed with the ivyTeam in advance - forced by the PM.

**Review by alexsuter — APPROVED** [review]
approval of everything except the logo change ;)

**Pull request merged**
