### PR TITLE
XIVY-10223 Add banners to download pages

### PR DESCRIPTION
**Pull request by jackra1n**
Did I forget anything? 🤔 

image
image
image
image

### CODE REVIEW

**Comment by alexsuter** [comment]
This Long Term Support version is no longer supported. Upgrade to the latest <LTS link>

**Comment by alexsuter** [comment]
what if you have an outdated Leading Edge Version?

**Comment by alexsuter** [comment]
please add tests in DownloadActionTest

**Comment by jackra1n** [comment]
Outdated LE:
image

**Pull request merged**
