### PR TITLE
XIYV-9790 Dedicated website for Axon Ivy Market

### PR DESCRIPTION
**Pull request by alexsuter**
The new market website is currently here: https://market-test.axonivya.myhostpoint.ch/

Any idea how to improve the header?

### CODE REVIEW

**Review by ivy-lli — APPROVED** [review]

**Comment by alexsuter** [comment]
No I wouldn't do that. Two complete independent sites. Market site is now faster, because it does not need parse all release infos just for the header of the header.

community.axonivy.com is also a standalone site

https://market.axonivy.com should be the only entrypoint to show the market.

**Comment by alexsuter** [comment]
I'll talk to Pascal about the layout.

**Comment by ivy-lli** [comment]
> No I wouldn't do that. Two complete independent sites. Market site is now faster, because it does not need parse all release infos just for the header of the header.
> 
> community.axonivy.com is also a standalone site
> 
> https://market.axonivy.com should be the only entrypoint to show the market.

ok that's right. I wasn't aware that this needs so much time...

**Comment by alexsuter** [comment]
@ivy-cst loves the header, so I just use the same header on the market side (without the download button). if someone like to change in future the ui, this is now possible.

**Pull request merged**
